import { defineStore } from "pinia";

export const useStore = defineStore("store", {
  state: () => ({
    cars: [],
    branches: [],
  }),

  actions: {
    fetchCars() {
      this.cars = [
        {
          id: 1,
          model: "Audi A1",
          type: "Hatchback",
          year: 2021,
          fuel: "Gasoline",
          price: 26450,
          image: "/assets/images/1.jpg",
          performance: "0-60 mph in 8.2 seconds, Top Speed 124 mph",
          engine: "1.4L TFSI",
          dimensions: "Length: 4.03m, Width: 1.74m, Height: 1.41m",
          seating: 5,
          safety: "Airbags, ABS, Lane Departure Warning, Stability Control",
          transmission: "Automatic",
          driveType: "FWD",
          horsepower: 150,
          torque: "250 Nm",
          stock: 15,
          branchId: 1,
        },
        {
          id: 2,
          model: "Audi A2",
          type: "Hatchback",
          year: 2021,
          fuel: "Diesel",
          price: 16720,
          image: "/assets/images/2.jpg",
          performance: "0-60 mph in 10.5 seconds, Top Speed 112 mph",
          engine: "1.6L TDI",
          dimensions: "Length: 3.83m, Width: 1.67m, Height: 1.55m",
          seating: 4,
          safety: "Airbags, ABS, Traction Control",
          transmission: "Manual",
          driveType: "FWD",
          horsepower: 100,
          torque: "210 Nm",
          stock: 8,
          branchId: 1,
        },
        {
          id: 3,
          model: "Audi A3",
          type: "Sedan",
          year: 2021,
          fuel: "Gasoline",
          price: 38200,
          image: "/assets/images/3.jpg",
          performance: "0-60 mph in 6.6 seconds, Top Speed 135 mph",
          engine: "2.0L TFSI",
          dimensions: "Length: 4.34m, Width: 1.81m, Height: 1.43m",
          seating: 5,
          safety: "Airbags, ABS, Lane Assist, Blind Spot Monitoring",
          transmission: "Automatic",
          driveType: "AWD",
          horsepower: 200,
          torque: "320 Nm",
          stock: 12,
          branchId: 1,
        },
        {
          id: 4,
          model: "Audi A4",
          type: "Sedan",
          year: 2021,
          fuel: "Hybrid",
          price: 46395,
          image: "/assets/images/4.jpg",
          performance: "0-60 mph in 5.3 seconds, Top Speed 155 mph",
          engine: "2.0L TFSI + Electric Motor",
          dimensions: "Length: 4.76m, Width: 1.84m, Height: 1.43m",
          seating: 5,
          safety: "Airbags, ABS, Collision Detection, Adaptive Cruise Control",
          transmission: "Automatic",
          driveType: "AWD",
          horsepower: 250,
          torque: "370 Nm",
          stock: 10,
          branchId: 2,
        },
        {
          id: 5,
          model: "Audi A5",
          type: "Coupe",
          year: 2021,
          fuel: "Gasoline",
          price: 47900,
          image: "/assets/images/5.jpg",
          performance: "0-60 mph in 5.1 seconds, Top Speed 155 mph",
          engine: "2.0L TFSI",
          dimensions: "Length: 4.67m, Width: 1.84m, Height: 1.37m",
          seating: 4,
          safety: "Airbags, ABS, Lane Departure Warning",
          transmission: "Automatic",
          driveType: "AWD",
          horsepower: 261,
          torque: "370 Nm",
          stock: 7,
          branchId: 2,
        },
        {
          id: 6,
          model: "Audi A6",
          type: "Sedan",
          year: 2021,
          fuel: "Diesel",
          price: 59450,
          image: "/assets/images/6.jpg",
          performance: "0-60 mph in 6.1 seconds, Top Speed 155 mph",
          engine: "3.0L TDI",
          dimensions: "Length: 4.94m, Width: 1.88m, Height: 1.46m",
          seating: 5,
          safety:
            "Airbags, ABS, Lane Departure Warning, Adaptive Cruise Control",
          transmission: "Automatic",
          driveType: "AWD",
          horsepower: 335,
          torque: "500 Nm",
          stock: 6,
          branchId: 3,
        },
        {
          id: 7,
          model: "Audi A7",
          type: "Sportback",
          year: 2021,
          fuel: "Gasoline",
          price: 73935,
          image: "/assets/images/7.jpg",
          performance: "0-60 mph in 5.2 seconds, Top Speed 155 mph",
          engine: "3.0L TFSI",
          dimensions: "Length: 4.97m, Width: 1.91m, Height: 1.42m",
          seating: 5,
          safety: "Airbags, ABS, Lane Assist, 360-Degree Camera",
          transmission: "Automatic",
          driveType: "AWD",
          horsepower: 335,
          torque: "500 Nm",
          stock: 5,
          branchId: 3,
        },
        {
          id: 8,
          model: "Audi A8",
          type: "Luxury Sedan",
          year: 2021,
          fuel: "Hybrid",
          price: 93295,
          image: "/assets/images/8.jpg",
          performance: "0-60 mph in 5.4 seconds, Top Speed 155 mph",
          engine: "3.0L TFSI + Electric Motor",
          dimensions: "Length: 5.17m, Width: 1.95m, Height: 1.47m",
          seating: 5,
          safety: "Airbags, ABS, Autonomous Emergency Braking, Night Vision",
          transmission: "Automatic",
          driveType: "AWD",
          horsepower: 443,
          torque: "700 Nm",
          stock: 4,
          branchId: 3,
        },
        {
          id: 9,
          model: "Audi Q7",
          type: "SUV",
          year: 2021,
          fuel: "Gasoline",
          price: 79195,
          image: "/assets/images/q7.jpg",
          performance: "0-60 mph in 5.7 seconds, Top Speed 130 mph",
          engine: "3.0L TFSI",
          dimensions: "Length: 5.05m, Width: 1.97m, Height: 1.74m",
          seating: 7,
          safety: "Airbags, ABS, Roll Stability Control, Blind Spot Monitoring",
          transmission: "Automatic",
          driveType: "AWD",
          horsepower: 335,
          torque: "500 Nm",
          stock: 9,
          branchId: 3,
        },
        {
          id: 10,
          model: "Audi R8",
          type: "Supercar",
          year: 2021,
          fuel: "Gasoline",
          price: 253290,
          image: "/assets/images/r8.jpg",
          performance: "0-60 mph in 3.1 seconds, Top Speed 205 mph",
          engine: "5.2L V10",
          dimensions: "Length: 4.42m, Width: 1.94m, Height: 1.24m",
          seating: 2,
          safety: "Airbags, ABS, Stability Control",
          transmission: "Automatic",
          driveType: "AWD",
          horsepower: 602,
          torque: "560 Nm",
          stock: 3,
          branchId: 2,
        },
      ];
    },
    fetchBranches() {
      this.branches = [
        {
          id: 1,
          name: "Baghdad",
          description: "Main Branch In City Center.",
          image: "/assets/images/b1.jpg",
          cars: [1, 2, 3],
        },
        {
          id: 2,
          name: "Basra",
          description: "Second Branch In South.",
          image: "/assets/images/b2.jpg",
          cars: [4, 5, 10],
        },
        {
          id: 3,
          name: "Erbil",
          description: "Third Branch In North.",
          image: "/assets/images/b3.jpg",
          cars: [6, 7, 8, 9],
        },
      ];
    },
  },
});
